# Generated by Django 3.0.6 on 2020-05-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='polarity_positive',
            field=models.BooleanField(default=False),
        ),
    ]
